$path = 'D:\SoLi-Food-Order-and-Deliver-App\apps\api\src\drizzle\seeds\seed.ts'
$c = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

# ── Helper: literal replace ──────────────────────────────────────────────────
function R($c, $old, $new) { $c.Replace($old, $new) }

# ── Restaurants ───────────────────────────────────────────────────────────────
$c = R $c "name: 'Ph? B?c'," "name: 'Phở Bắc',"
$c = R $c "description: 'Ph? B?c ch?nh hi?u ? n??c d?ng h?m x??ng 12 ti?ng.'," "description: 'Phở Bắc chính hiệu — nước dùng hầm xương 12 tiếng.',"
$c = R $c "address: '45 Nguy?n Hu?, Qu?n 1, TP.HCM'," "address: '45 Nguyễn Huệ, Quận 1, TP.HCM',"
$c = R $c "name: 'B?p ??ng C?a'," "name: 'Bếp Đóng Cửa',"
$c = R $c "description: 'T?m ??ng c?a ?? c?i t?o.'," "description: 'Tạm đóng cửa để cải tạo.',"
$c = R $c "address: '12 Hai B? Tr?ng, Qu?n 3, TP.HCM'," "address: '12 Hai Bà Trưng, Quận 3, TP.HCM',"
$c = R $c "name: 'C?m T?m S?i G?n'," "name: 'Cơm Tấm Sài Gòn',"
$c = R $c "description: 'C?m t?m s??n n??ng, b? ch? ? ??c s?n mi?n Nam.'," "description: 'Cơm tấm sườn nướng, bì chả — đặc sản miền Nam.',"
$c = R $c "address: '78 L? L?i, Qu?n 1, TP.HCM'," "address: '78 Lê Lợi, Quận 1, TP.HCM',"
$c = R $c "description: 'Th?t n??ng H?n Qu?c, kimchi, bibimbap ch?nh g?c.'," "description: 'Thịt nướng Hàn Quốc, kimchi, bibimbap chính gốc.',"
$c = R $c "address: '30 Nguy?n V?n Linh, Qu?n 7, TP.HCM'," "address: '30 Nguyễn Văn Linh, Quận 7, TP.HCM',"
$c = R $c "description: 'Sushi v? sashimi Nh?t B?n ? nguy?n li?u nh?p kh?u.'," "description: 'Sushi và sashimi Nhật Bản — nguyên liệu nhập khẩu.',"
$c = R $c "address: '5 Phan ??ng L?u, B?nh Th?nh, TP.HCM'," "address: '5 Phan Đăng Lưu, Bình Thạnh, TP.HCM',"

# ── Delivery zones ────────────────────────────────────────────────────────────
$c = R $c "name: 'N?i th?nh (2 km)'," "name: 'Nội thành (2 km)',"
$c = R $c "name: 'To?n th?nh (5 km)'," "name: 'Toàn thành (5 km)',"
$c = R $c "name: 'Khu v?c giao h?ng (3 km)'," "name: 'Khu vực giao hàng (3 km)',"
$c = R $c "name: 'M? r?ng (5 km)'," "name: 'Mở rộng (5 km)',"
$c = R $c "name: 'Qu?n 7 n?i b? (2 km)'," "name: 'Quận 7 nội bộ (2 km)',"
$c = R $c "name: 'Li?n qu?n (8 km)'," "name: 'Liên quận (8 km)',"

# ── Menu items ────────────────────────────────────────────────────────────────
$c = R $c "name: 'Ph? B? T?i N?m'," "name: 'Phở Bò Tái Nạm',"
$c = R $c "'Ph? b? truy?n th?ng ? n??c d?ng h?m x??ng b? 12 ti?ng, t?i + n?m.'" "'Phở bò truyền thống — nước dùng hầm xương bò 12 tiếng, tái + nạm.'"
$c = R $c "name: 'Ph? G?'," "name: 'Phở Gà',"
$c = R $c "'Ph? g? ta ? n??c d?ng thanh ng?t t? nhi?n t? x??ng g?.'" "'Phở gà ta — nước dùng thanh ngọt tự nhiên từ xương gà.'"
$c = R $c "name: 'B?n B? Hu?'," "name: 'Bún Bò Huế',"
$c = R $c "'B?n b? Hu? cay ??c tr?ng ? m?m ru?c, s?, ?t.'" "'Bún bò Huế cay đặc trưng — mắm ruốc, sả, ớt.'"
$c = R $c "name: 'B?nh Cu?n'," "name: 'Bánh Cuốn',"
$c = R $c "'B?nh cu?n nh?n th?t b?m, m?c nh? ? ?n k?m ch? l?a v? n??c m?m.'" "'Bánh cuốn nhân thịt băm, mộc nhĩ — ăn kèm chả lụa và nước mắm.'"
$c = R $c "name: 'Tr? ??'," "name: 'Trà Đá',"
$c = R $c "'Tr? ?? mi?n ph? khi d?ng t?i b?n.'" "'Trà đá miễn phí khi dùng tại bàn.'"
$c = R $c "name: 'C?m T?m S??n N??ng'," "name: 'Cơm Tấm Sườn Nướng',"
$c = R $c "'C?m t?m k?m s??n n??ng than hoa, tr?ng chi?n, ?? chua.'" "'Cơm tấm kèm sườn nướng than hoa, trứng chiên, đồ chua.'"
$c = R $c "name: 'C?m T?m B? Ch?'," "name: 'Cơm Tấm Bì Chả',"
$c = R $c "'C?m t?m k?m b? l?n v? ch? tr?ng h?p.'" "'Cơm tấm kèm bì lợn và chả trứng hấp.'"
$c = R $c "name: 'B?nh M? Th?t N??ng'," "name: 'Bánh Mì Thịt Nướng',"
$c = R $c "'B?nh m? gi?n nh?n th?t heo n??ng, ?? chua, rau th?m, t??ng ?t.'" "'Bánh mì giòn nhân thịt heo nướng, đồ chua, rau thơm, tương ớt.'"
$c = R $c "name: 'C?m Chay'," "name: 'Cơm Chay',"
$c = R $c "'C?m tr?ng k?m ??u ph?, rau c? x?o v? canh chay.'" "'Cơm trắng kèm đậu phụ, rau củ xào và canh chay.'"
$c = R $c "name: 'N??c Ng?t'," "name: 'Nước Ngọt',"
$c = R $c "'Coca-Cola, Sprite, 7Up ? lon 330ml.'" "'Coca-Cola, Sprite, 7Up — lon 330ml.'"
$c = R $c "name: 'Th?t N??ng H?n Qu?c'," "name: 'Thịt Nướng Hàn Quốc',"
$c = R $c "'B? th?t n??ng ba ch? v? ba r?i ? ??p s?t gochujang, ?n k?m rau cu?n.'" "'Bộ thịt nướng ba chỉ và ba rọi — ướp sốt gochujang, ăn kèm rau cuốn.'"
$c = R $c "'Canh kimchi h?m th?t heo v? ??u ph? ? cay ??m ??.'" "'Canh kimchi hầm thịt heo và đậu phụ — cay đậm đà.'"
$c = R $c "'C?m tr?n H?n Qu?c ? rau namul, th?t b?, tr?ng l?ng ??o, t??ng gochujang.'" "'Cơm trộn Hàn Quốc — rau namul, thịt bò, trứng lòng đào, tương gochujang.'"
$c = R $c "name: 'Tr? S?a Tr?n Ch?u'," "name: 'Trà Sữa Trân Châu',"
$c = R $c "'Tr? s?a H?n Qu?c ? tr?n ch?u ?en, c? th? ch?n m?c ??ng v? ??.'" "'Trà sữa Hàn Quốc — trân châu đen, có thể chọn mức đường và đá.'"
$c = R $c "name: 'Sushi C? H?i'," "name: 'Sushi Cá Hồi',"
$c = R $c "'Sushi c? h?i Na Uy nh?p kh?u ? 8 mi?ng.'" "'Sushi cá hồi Na Uy nhập khẩu — 8 miếng.'"
$c = R $c "name: 'Sashimi C? Ng?'," "name: 'Sashimi Cá Ngừ',"
$c = R $c "'Sashimi c? ng? ??i d??ng th?i l?t m?ng ? 10 l?t.'" "'Sashimi cá ngừ đại dương thái lát mỏng — 10 lát.'"
$c = R $c '"b?nh m?"' '"bánh mì"'
$c = R $c "name: 'B?nh M? C? H?i'," "name: 'Bánh Mì Cá Hồi',"
$c = R $c "'B?nh m? Nh?t B?n nh?n c? h?i s?t teriyaki v? rau m?m.'" "'Bánh mì Nhật Bản nhân cá hồi sốt teriyaki và rau mầm.'"
$c = R $c "name: 'Tr? Xanh Nh?t B?n'," "name: 'Trà Xanh Nhật Bản',"
$c = R $c "'Matcha latte n?ng / l?nh ? matcha Uji Kyoto grade A.'" "'Matcha latte nóng / lạnh — matcha Uji Kyoto grade A.'"

# ── Modifier groups ───────────────────────────────────────────────────────────
$c = R $c "name: 'K?ch c?'," "name: 'Kích cỡ',"
$c = R $c "name: 'Topping th?m'," "name: 'Topping thêm',"
$c = R $c "name: '?? cay'," "name: 'Độ cay',"
$c = R $c "name: '??ng'," "name: 'Đường',"
$c = R $c "name: 'Ph?n th?m'," "name: 'Phần thêm',"
$c = R $c "name: 'C? c?m'," "name: 'Cỡ cơm',"
$c = R $c "name: 'S?t'," "name: 'Sốt',"
$c = R $c "name: 'Lo?i th?t'," "name: 'Loại thịt',"
$c = R $c "name: 'Ph?n ?n'," "name: 'Phần ăn',"
$c = R $c "name: 'M?c ??ng'," "name: 'Mức đường',"
$c = R $c "name: 'L??ng ??'," "name: 'Lượng đá',"
$c = R $c "name: 'S? l??ng mi?ng'," "name: 'Số lượng miếng',"
$c = R $c "name: 'S?t ch?m'," "name: 'Sốt chấm',"
$c = R $c "name: 'Nhi?t ??'," "name: 'Nhiệt độ',"
$c = R $c "name: 'N?ng ?? matcha'," "name: 'Nồng độ matcha',"

# ── Modifier options ──────────────────────────────────────────────────────────
$c = R $c "name: 'T? nh?'," "name: 'Tô nhỏ',"
$c = R $c "name: 'T? v?a'," "name: 'Tô vừa',"
$c = R $c "name: 'T? l?n'," "name: 'Tô lớn',"
$c = R $c "name: 'Th?m t?i'," "name: 'Thêm tái',"
$c = R $c "name: 'Th?m n?m'," "name: 'Thêm nạm',"
$c = R $c "name: 'Th?m g?n'," "name: 'Thêm gân',"
$c = R $c "name: 'Th?m s?ch'," "name: 'Thêm sách',"
$c = R $c "name: 'Kh?ng cay'," "name: 'Không cay',"
$c = R $c "name: 'Cay v?a'," "name: 'Cay vừa',"
$c = R $c "name: 'Cay nhi?u'," "name: 'Cay nhiều',"
$c = R $c "name: 'Th?m ch? cua'," "name: 'Thêm chả cua',"
$c = R $c "name: 'Th?m ch? heo'," "name: 'Thêm chả heo',"
$c = R $c "name: 'Kh?ng ??ng'," "name: 'Không đường',"
$c = R $c "name: '?t ??ng'," "name: 'Ít đường',"
$c = R $c "name: 'B?nh th??ng'," "name: 'Bình thường',"
$c = R $c "name: 'Tr?ng ?p la'," "name: 'Trứng ốp la',"
$c = R $c "name: 'Ch? cua'," "name: 'Chả cua',"
$c = R $c "name: 'Th?m b?'," "name: 'Thêm bì',"
$c = R $c "name: '?t c?m'," "name: 'Ít cơm',"
$c = R $c "name: 'Nhi?u c?m'," "name: 'Nhiều cơm',"
$c = R $c "name: 'D?a leo'," "name: 'Dưa leo',"
$c = R $c "name: '?? chua'," "name: 'Đồ chua',"
$c = R $c "name: 'Rau m?i'," "name: 'Rau mùi',"
$c = R $c "name: 'Kh?ng rau'," "name: 'Không rau',"
$c = R $c "name: 'T??ng ?t'," "name: 'Tương ớt',"
$c = R $c "name: 'T??ng ?en'," "name: 'Tương đen',"
$c = R $c "name: 'Kh?ng s?t'," "name: 'Không sốt',"
$c = R $c "name: 'Ba ch? heo'," "name: 'Ba chỉ heo',"
$c = R $c "name: 'C? heo'," "name: 'Cổ heo',"
$c = R $c "name: 'B? ba r?i'," "name: 'Bò ba rọi',"
$c = R $c "name: '1 ng??i'," "name: '1 người',"
$c = R $c "name: '2 ng??i'," "name: '2 người',"
$c = R $c "name: '3 ng??i'," "name: '3 người',"
$c = R $c "name: '0% ??ng'," "name: '0% đường',"
$c = R $c "name: '30% ??ng'," "name: '30% đường',"
$c = R $c "name: '50% ??ng'," "name: '50% đường',"
$c = R $c "name: '100% ??ng'," "name: '100% đường',"
$c = R $c "name: 'Kh?ng ??'," "name: 'Không đá',"
$c = R $c "name: '?t ??'," "name: 'Ít đá',"
$c = R $c "name: 'Nhi?u ??'," "name: 'Nhiều đá',"
$c = R $c "name: 'Tr?n ch?u ?en'," "name: 'Trân châu đen',"
$c = R $c "name: 'Th?ch'," "name: 'Thạch',"
$c = R $c "name: 'Kem tr?ng'," "name: 'Kem trứng',"
$c = R $c "name: 'Th?t b?'," "name: 'Thịt bò',"
$c = R $c "name: '??u ph?'," "name: 'Đậu phụ',"
$c = R $c "name: 'Tr?ng s?ng'," "name: 'Trứng sống',"
$c = R $c "name: '8 mi?ng'," "name: '8 miếng',"
$c = R $c "name: '12 mi?ng'," "name: '12 miếng',"
$c = R $c "name: '16 mi?ng'," "name: '16 miếng',"
$c = R $c "name: 'T??ng g?ng'," "name: 'Tương gừng',"
$c = R $c "name: 'S?t cam yuzu'," "name: 'Sốt cam yuzu',"
$c = R $c "name: 'N?ng'," "name: 'Nóng',"
$c = R $c "name: 'L?nh'," "name: 'Lạnh',"
$c = R $c "name: 'Nh?t'," "name: 'Nhạt',"
$c = R $c "name: '??m'," "name: 'Đậm',"

# ── Write back as UTF-8 (no BOM) ─────────────────────────────────────────────
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($path, $c, $utf8NoBom)
Write-Host "Done. File written as UTF-8."
